\hypertarget{classv8_1_1TryCatch}{}\section{v8\+:\+:Try\+Catch Class Reference}
\label{classv8_1_1TryCatch}\index{v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}}


{\ttfamily \#include $<$v8.\+h$>$}

\subsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
\mbox{\hyperlink{classv8_1_1TryCatch_a623ce624491b383fae60c05d2aeefb1a}{Try\+Catch}} (\mbox{\hyperlink{classv8_1_1Isolate}{Isolate}} $\ast$isolate)
\item 
\mbox{\hyperlink{classv8_1_1TryCatch_a2c9ad4b40d17dd31c6dd020736b30679}{$\sim$\+Try\+Catch}} ()
\item 
bool \mbox{\hyperlink{classv8_1_1TryCatch_ab77b36a4adf5681da59abfe43adc4e4e}{Has\+Caught}} () const
\item 
bool \mbox{\hyperlink{classv8_1_1TryCatch_ae94d0f0d695dbfecbfcdeb48716b367f}{Can\+Continue}} () const
\item 
bool \mbox{\hyperlink{classv8_1_1TryCatch_a3175391e782afc092495616b4d35b91b}{Has\+Terminated}} () const
\item 
\mbox{\hyperlink{classv8_1_1Local}{Local}}$<$ \mbox{\hyperlink{classv8_1_1Value}{Value}} $>$ \mbox{\hyperlink{classv8_1_1TryCatch_ab8c3a1dbb38e6fd00e37436034daf707}{Re\+Throw}} ()
\item 
\mbox{\hyperlink{classv8_1_1Local}{Local}}$<$ \mbox{\hyperlink{classv8_1_1Value}{Value}} $>$ \mbox{\hyperlink{classv8_1_1TryCatch_acad32566761cace7762e023c9e443323}{Exception}} () const
\item 
\mbox{\hyperlink{classv8_1_1TryCatch_a68d99863957fee038877a2d710cd0958}{V8\+\_\+\+D\+E\+P\+R\+E\+C\+A\+T\+ED}} (\char`\"{}Use maybe version.\char`\"{}, Local$<$ \mbox{\hyperlink{classv8_1_1Value}{Value}} $>$ \mbox{\hyperlink{classv8_1_1StackTrace}{Stack\+Trace}}() const)
\item 
\mbox{\Hypertarget{classv8_1_1TryCatch_ac8aabb4b19ac590fd6e6aa892bed9af4}\label{classv8_1_1TryCatch_ac8aabb4b19ac590fd6e6aa892bed9af4}} 
V8\+\_\+\+W\+A\+R\+N\+\_\+\+U\+N\+U\+S\+E\+D\+\_\+\+R\+E\+S\+U\+LT \mbox{\hyperlink{classv8_1_1MaybeLocal}{Maybe\+Local}}$<$ \mbox{\hyperlink{classv8_1_1Value}{Value}} $>$ {\bfseries Stack\+Trace} (\mbox{\hyperlink{classv8_1_1Local}{Local}}$<$ \mbox{\hyperlink{classv8_1_1Context}{Context}} $>$ context) const
\item 
\mbox{\hyperlink{classv8_1_1Local}{Local}}$<$ \mbox{\hyperlink{classv8_1_1Message}{v8\+::\+Message}} $>$ \mbox{\hyperlink{classv8_1_1TryCatch_a91a41367c87e7a59ada09bcb9aae76c0}{Message}} () const
\item 
void \mbox{\hyperlink{classv8_1_1TryCatch_a3aae8acab4c99b374b7d782763d4c8e1}{Reset}} ()
\item 
void \mbox{\hyperlink{classv8_1_1TryCatch_a032cd889d76bd596e2616df11ced8682}{Set\+Verbose}} (bool value)
\item 
bool \mbox{\hyperlink{classv8_1_1TryCatch_aa4e77abd0d6790700442153cb036517f}{Is\+Verbose}} () const
\item 
void \mbox{\hyperlink{classv8_1_1TryCatch_a541b8fa6951bd5a439692c22d5c7b73c}{Set\+Capture\+Message}} (bool value)
\item 
\mbox{\Hypertarget{classv8_1_1TryCatch_a7368ba9d21e9bddef45a76f537f1900e}\label{classv8_1_1TryCatch_a7368ba9d21e9bddef45a76f537f1900e}} 
{\bfseries Try\+Catch} (const \mbox{\hyperlink{classv8_1_1TryCatch}{Try\+Catch}} \&)=delete
\item 
\mbox{\Hypertarget{classv8_1_1TryCatch_a9fec223509a6d7095b3088871a6084ce}\label{classv8_1_1TryCatch_a9fec223509a6d7095b3088871a6084ce}} 
void {\bfseries operator=} (const \mbox{\hyperlink{classv8_1_1TryCatch}{Try\+Catch}} \&)=delete
\end{DoxyCompactItemize}
\subsection*{Static Public Member Functions}
\begin{DoxyCompactItemize}
\item 
static void $\ast$ \mbox{\hyperlink{classv8_1_1TryCatch_a164f5def2f8fa5deb6bcf06fb50fbff2}{J\+S\+Stack\+Comparable\+Address}} (\mbox{\hyperlink{classv8_1_1TryCatch}{Try\+Catch}} $\ast$handler)
\end{DoxyCompactItemize}
\subsection*{Friends}
\begin{DoxyCompactItemize}
\item 
\mbox{\Hypertarget{classv8_1_1TryCatch_a438c8b784134d31d7a50bc60098d8ba1}\label{classv8_1_1TryCatch_a438c8b784134d31d7a50bc60098d8ba1}} 
class {\bfseries internal\+::\+Isolate}
\end{DoxyCompactItemize}


\subsection{Detailed Description}
An external exception handler. 

\subsection{Constructor \& Destructor Documentation}
\mbox{\Hypertarget{classv8_1_1TryCatch_a623ce624491b383fae60c05d2aeefb1a}\label{classv8_1_1TryCatch_a623ce624491b383fae60c05d2aeefb1a}} 
\index{v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}!Try\+Catch@{Try\+Catch}}
\index{Try\+Catch@{Try\+Catch}!v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}}
\subsubsection{\texorpdfstring{Try\+Catch()}{TryCatch()}}
{\footnotesize\ttfamily v8\+::\+Try\+Catch\+::\+Try\+Catch (\begin{DoxyParamCaption}\item[{\mbox{\hyperlink{classv8_1_1Isolate}{Isolate}} $\ast$}]{isolate }\end{DoxyParamCaption})\hspace{0.3cm}{\ttfamily [explicit]}}

Creates a new try/catch block and registers it with \mbox{\hyperlink{namespacev8}{v8}}. Note that all \mbox{\hyperlink{classv8_1_1TryCatch}{Try\+Catch}} blocks should be stack allocated because the memory location itself is compared against Java\+Script try/catch blocks. \mbox{\Hypertarget{classv8_1_1TryCatch_a2c9ad4b40d17dd31c6dd020736b30679}\label{classv8_1_1TryCatch_a2c9ad4b40d17dd31c6dd020736b30679}} 
\index{v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}!````~Try\+Catch@{$\sim$\+Try\+Catch}}
\index{````~Try\+Catch@{$\sim$\+Try\+Catch}!v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}}
\subsubsection{\texorpdfstring{$\sim$\+Try\+Catch()}{~TryCatch()}}
{\footnotesize\ttfamily v8\+::\+Try\+Catch\+::$\sim$\+Try\+Catch (\begin{DoxyParamCaption}{ }\end{DoxyParamCaption})}

Unregisters and deletes this try/catch block. 

\subsection{Member Function Documentation}
\mbox{\Hypertarget{classv8_1_1TryCatch_ae94d0f0d695dbfecbfcdeb48716b367f}\label{classv8_1_1TryCatch_ae94d0f0d695dbfecbfcdeb48716b367f}} 
\index{v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}!Can\+Continue@{Can\+Continue}}
\index{Can\+Continue@{Can\+Continue}!v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}}
\subsubsection{\texorpdfstring{Can\+Continue()}{CanContinue()}}
{\footnotesize\ttfamily bool v8\+::\+Try\+Catch\+::\+Can\+Continue (\begin{DoxyParamCaption}{ }\end{DoxyParamCaption}) const}

For certain types of exceptions, it makes no sense to continue execution.

If Can\+Continue returns false, the correct action is to perform any C++ cleanup needed and then return. If Can\+Continue returns false and Has\+Terminated returns true, it is possible to call Cancel\+Terminate\+Execution in order to continue calling into the engine. \mbox{\Hypertarget{classv8_1_1TryCatch_acad32566761cace7762e023c9e443323}\label{classv8_1_1TryCatch_acad32566761cace7762e023c9e443323}} 
\index{v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}!Exception@{Exception}}
\index{Exception@{Exception}!v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}}
\subsubsection{\texorpdfstring{Exception()}{Exception()}}
{\footnotesize\ttfamily \mbox{\hyperlink{classv8_1_1Local}{Local}}$<$\mbox{\hyperlink{classv8_1_1Value}{Value}}$>$ v8\+::\+Try\+Catch\+::\+Exception (\begin{DoxyParamCaption}{ }\end{DoxyParamCaption}) const}

Returns the exception caught by this try/catch block. If no exception has been caught an empty handle is returned.

The returned handle is valid until this \mbox{\hyperlink{classv8_1_1TryCatch}{Try\+Catch}} block has been destroyed. \mbox{\Hypertarget{classv8_1_1TryCatch_ab77b36a4adf5681da59abfe43adc4e4e}\label{classv8_1_1TryCatch_ab77b36a4adf5681da59abfe43adc4e4e}} 
\index{v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}!Has\+Caught@{Has\+Caught}}
\index{Has\+Caught@{Has\+Caught}!v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}}
\subsubsection{\texorpdfstring{Has\+Caught()}{HasCaught()}}
{\footnotesize\ttfamily bool v8\+::\+Try\+Catch\+::\+Has\+Caught (\begin{DoxyParamCaption}{ }\end{DoxyParamCaption}) const}

Returns true if an exception has been caught by this try/catch block. \mbox{\Hypertarget{classv8_1_1TryCatch_a3175391e782afc092495616b4d35b91b}\label{classv8_1_1TryCatch_a3175391e782afc092495616b4d35b91b}} 
\index{v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}!Has\+Terminated@{Has\+Terminated}}
\index{Has\+Terminated@{Has\+Terminated}!v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}}
\subsubsection{\texorpdfstring{Has\+Terminated()}{HasTerminated()}}
{\footnotesize\ttfamily bool v8\+::\+Try\+Catch\+::\+Has\+Terminated (\begin{DoxyParamCaption}{ }\end{DoxyParamCaption}) const}

Returns true if an exception has been caught due to script execution being terminated.

There is no Java\+Script representation of an execution termination exception. Such exceptions are thrown when the Terminate\+Execution methods are called to terminate a long-\/running script.

If such an exception has been thrown, Has\+Terminated will return true, indicating that it is possible to call Cancel\+Terminate\+Execution in order to continue calling into the engine. \mbox{\Hypertarget{classv8_1_1TryCatch_aa4e77abd0d6790700442153cb036517f}\label{classv8_1_1TryCatch_aa4e77abd0d6790700442153cb036517f}} 
\index{v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}!Is\+Verbose@{Is\+Verbose}}
\index{Is\+Verbose@{Is\+Verbose}!v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}}
\subsubsection{\texorpdfstring{Is\+Verbose()}{IsVerbose()}}
{\footnotesize\ttfamily bool v8\+::\+Try\+Catch\+::\+Is\+Verbose (\begin{DoxyParamCaption}{ }\end{DoxyParamCaption}) const}

Returns true if verbosity is enabled. \mbox{\Hypertarget{classv8_1_1TryCatch_a164f5def2f8fa5deb6bcf06fb50fbff2}\label{classv8_1_1TryCatch_a164f5def2f8fa5deb6bcf06fb50fbff2}} 
\index{v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}!J\+S\+Stack\+Comparable\+Address@{J\+S\+Stack\+Comparable\+Address}}
\index{J\+S\+Stack\+Comparable\+Address@{J\+S\+Stack\+Comparable\+Address}!v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}}
\subsubsection{\texorpdfstring{J\+S\+Stack\+Comparable\+Address()}{JSStackComparableAddress()}}
{\footnotesize\ttfamily static void$\ast$ v8\+::\+Try\+Catch\+::\+J\+S\+Stack\+Comparable\+Address (\begin{DoxyParamCaption}\item[{\mbox{\hyperlink{classv8_1_1TryCatch}{Try\+Catch}} $\ast$}]{handler }\end{DoxyParamCaption})\hspace{0.3cm}{\ttfamily [inline]}, {\ttfamily [static]}}

There are cases when the raw address of C++ \mbox{\hyperlink{classv8_1_1TryCatch}{Try\+Catch}} object cannot be used for comparisons with addresses into the JS stack. The cases are\+: 1) A\+RM, A\+R\+M64 and M\+I\+PS simulators which have separate JS stack. 2) Address sanitizer allocates local C++ object in the heap when Use\+After\+Return mode is enabled. This method returns address that can be used for comparisons with addresses into the JS stack. When neither simulator nor A\+S\+AN\textquotesingle{}s Use\+After\+Return is enabled, then the address returned will be the address of the C++ try catch handler itself. \mbox{\Hypertarget{classv8_1_1TryCatch_a91a41367c87e7a59ada09bcb9aae76c0}\label{classv8_1_1TryCatch_a91a41367c87e7a59ada09bcb9aae76c0}} 
\index{v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}!Message@{Message}}
\index{Message@{Message}!v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}}
\subsubsection{\texorpdfstring{Message()}{Message()}}
{\footnotesize\ttfamily \mbox{\hyperlink{classv8_1_1Local}{Local}}$<$\mbox{\hyperlink{classv8_1_1Message}{v8\+::\+Message}}$>$ v8\+::\+Try\+Catch\+::\+Message (\begin{DoxyParamCaption}{ }\end{DoxyParamCaption}) const}

Returns the message associated with this exception. If there is no message associated an empty handle is returned.

The returned handle is valid until this \mbox{\hyperlink{classv8_1_1TryCatch}{Try\+Catch}} block has been destroyed. \mbox{\Hypertarget{classv8_1_1TryCatch_a3aae8acab4c99b374b7d782763d4c8e1}\label{classv8_1_1TryCatch_a3aae8acab4c99b374b7d782763d4c8e1}} 
\index{v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}!Reset@{Reset}}
\index{Reset@{Reset}!v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}}
\subsubsection{\texorpdfstring{Reset()}{Reset()}}
{\footnotesize\ttfamily void v8\+::\+Try\+Catch\+::\+Reset (\begin{DoxyParamCaption}{ }\end{DoxyParamCaption})}

Clears any exceptions that may have been caught by this try/catch block. After this method has been called, \mbox{\hyperlink{classv8_1_1TryCatch_ab77b36a4adf5681da59abfe43adc4e4e}{Has\+Caught()}} will return false. Cancels the scheduled exception if it is caught and \mbox{\hyperlink{classv8_1_1TryCatch_ab8c3a1dbb38e6fd00e37436034daf707}{Re\+Throw()}} is not called before.

It is not necessary to clear a try/catch block before using it again; if another exception is thrown the previously caught exception will just be overwritten. However, it is often a good idea since it makes it easier to determine which operation threw a given exception. \mbox{\Hypertarget{classv8_1_1TryCatch_ab8c3a1dbb38e6fd00e37436034daf707}\label{classv8_1_1TryCatch_ab8c3a1dbb38e6fd00e37436034daf707}} 
\index{v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}!Re\+Throw@{Re\+Throw}}
\index{Re\+Throw@{Re\+Throw}!v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}}
\subsubsection{\texorpdfstring{Re\+Throw()}{ReThrow()}}
{\footnotesize\ttfamily \mbox{\hyperlink{classv8_1_1Local}{Local}}$<$\mbox{\hyperlink{classv8_1_1Value}{Value}}$>$ v8\+::\+Try\+Catch\+::\+Re\+Throw (\begin{DoxyParamCaption}{ }\end{DoxyParamCaption})}

Throws the exception caught by this \mbox{\hyperlink{classv8_1_1TryCatch}{Try\+Catch}} in a way that avoids it being caught again by this same \mbox{\hyperlink{classv8_1_1TryCatch}{Try\+Catch}}. As with Throw\+Exception it is illegal to execute any Java\+Script operations after calling Re\+Throw; the caller must return immediately to where the exception is caught. \mbox{\Hypertarget{classv8_1_1TryCatch_a541b8fa6951bd5a439692c22d5c7b73c}\label{classv8_1_1TryCatch_a541b8fa6951bd5a439692c22d5c7b73c}} 
\index{v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}!Set\+Capture\+Message@{Set\+Capture\+Message}}
\index{Set\+Capture\+Message@{Set\+Capture\+Message}!v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}}
\subsubsection{\texorpdfstring{Set\+Capture\+Message()}{SetCaptureMessage()}}
{\footnotesize\ttfamily void v8\+::\+Try\+Catch\+::\+Set\+Capture\+Message (\begin{DoxyParamCaption}\item[{bool}]{value }\end{DoxyParamCaption})}

\mbox{\hyperlink{classv8_1_1Set}{Set}} whether or not this \mbox{\hyperlink{classv8_1_1TryCatch}{Try\+Catch}} should capture a \mbox{\hyperlink{classv8_1_1Message}{Message}} object which holds source information about where the exception occurred. True by default. \mbox{\Hypertarget{classv8_1_1TryCatch_a032cd889d76bd596e2616df11ced8682}\label{classv8_1_1TryCatch_a032cd889d76bd596e2616df11ced8682}} 
\index{v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}!Set\+Verbose@{Set\+Verbose}}
\index{Set\+Verbose@{Set\+Verbose}!v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}}
\subsubsection{\texorpdfstring{Set\+Verbose()}{SetVerbose()}}
{\footnotesize\ttfamily void v8\+::\+Try\+Catch\+::\+Set\+Verbose (\begin{DoxyParamCaption}\item[{bool}]{value }\end{DoxyParamCaption})}

\mbox{\hyperlink{classv8_1_1Set}{Set}} verbosity of the external exception handler.

By default, exceptions that are caught by an external exception handler are not reported. Call Set\+Verbose with true on an external exception handler to have exceptions caught by the handler reported as if they were not caught. \mbox{\Hypertarget{classv8_1_1TryCatch_a68d99863957fee038877a2d710cd0958}\label{classv8_1_1TryCatch_a68d99863957fee038877a2d710cd0958}} 
\index{v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}!V8\+\_\+\+D\+E\+P\+R\+E\+C\+A\+T\+ED@{V8\+\_\+\+D\+E\+P\+R\+E\+C\+A\+T\+ED}}
\index{V8\+\_\+\+D\+E\+P\+R\+E\+C\+A\+T\+ED@{V8\+\_\+\+D\+E\+P\+R\+E\+C\+A\+T\+ED}!v8\+::\+Try\+Catch@{v8\+::\+Try\+Catch}}
\subsubsection{\texorpdfstring{V8\+\_\+\+D\+E\+P\+R\+E\+C\+A\+T\+E\+D()}{V8\_DEPRECATED()}}
{\footnotesize\ttfamily v8\+::\+Try\+Catch\+::\+V8\+\_\+\+D\+E\+P\+R\+E\+C\+A\+T\+ED (\begin{DoxyParamCaption}\item[{\char`\"{}Use maybe version.\char`\"{}}]{,  }\item[{\mbox{\hyperlink{classv8_1_1Local}{Local}}$<$ \mbox{\hyperlink{classv8_1_1Value}{Value}} $>$ \mbox{\hyperlink{classv8_1_1StackTrace}{Stack\+Trace}}()}]{const }\end{DoxyParamCaption})}

Returns the .stack property of the thrown object. If no .stack property is present an empty handle is returned. 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
v8/include/v8.\+h\end{DoxyCompactItemize}
